version: '2'
services:
  nginx:
    container_name: web
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./webroot:/webroot
      - ./logs/nginx_access.log:/var/log/nginx/access.log
      - ./logs/nginx_error.log:/var/log/nginx/error.log
      - ./config/vhosts.conf:/etc/nginx/conf.d/default.conf
      #- ./src/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
    links:
      - "php55:php55"

  php54:
    container_name: php54
    image: php:5.4-fpm
    volumes:
      - ./webroot:/var/www/html
      - ./webroot:/webroot
      - ./logs/:/logs/
      - ./config/php-fpm.d/www.conf:/usr/local/etc/php-fpm.conf
      - ./config/php.ini:/usr/local/etc/php/php.ini

  php55:
    container_name: php55
    image: php:5.5-fpm
    volumes:
      - ./webroot:/var/www/html
      - ./webroot:/webroot
      - ./logs/:/logs/
      - ./config/php-fpm.d/www.conf:/usr/local/etc/php-fpm.conf
      - ./config/php.ini:/usr/local/etc/php/php.ini

  php56:
    container_name: php56
    image: php:5.6-fpm
    volumes:
      - ./webroot:/var/www/html
      - ./webroot:/webroot
      - ./logs/:/logs/
      - ./config/php-fpm.d/www.conf:/usr/local/etc/php-fpm.conf
      - ./config/php.ini:/usr/local/etc/php/php.ini
